### PR TITLE
Use symlinks on windows and add doctor

### PR DESCRIPTION
**Pull request by jolheiser**
The only remaining question is how to deal with current windows setups. 

Should we build in a migration system? In this case, a one-time scan for batch files and convert them to symlinks?

### CODE REVIEW

**Comment by candrewlee14** [comment]
It seems like some kind of migration would be good, but in future versions, we wouldn't want that maintenance bloat unless it's extensible.

In a two-birds-with-one-stone feature, we could create `webman env freeze > out.yaml` which takes all of our currently used binaries and puts them in a yaml file. Then `webman env create --name FooEnv --file out.yaml` or `webman env install out.yaml` installs the packages if not installed, then creates all the symlinks for this environment. Regular installs would be tracked in a `base` env. Freeze would use all the `using.yml` files to identify currently used binaries and versions.

For a migration, users who installed before this feature could freeze their environment (since they have the `using.yml` files) and restore from that environment file. Users with this feature have nice environments that they can create, delete (more to talk about), and switch.

What do you think about this?

**Comment by jolheiser** [comment]
I do like the idea of `freeze`, especially for things like dotfiles to configure a specific environment.

That being said, I don't know that I would want to combine it with this PR specifically.

As another alternative (and even something that could live alongside), what about a `doctor` subcommand?
That way it's only ran when a user wants to, and it can be extended by future versions by adding more checks.

**Comment by candrewlee14** [comment]
Yeah, I wouldn't want all that env stuff to be part of this PR. 

I think a doctor subcommand that rebuilds the bin symlinks from the using.yml files should be good for now, and that logic would translate easily to freezing or switching an environment. 

What other checks/fixes might the doctor command do, just for the sake of brainstorming?

**Comment by jolheiser** [comment]
Things like when I nested the recipes dir, it could have detected and fixed it.

Maybe even when we have schema changes, a way to detect and convert?

**Comment by jolheiser** [comment]
@candrewlee14 How does this look?

I've added a check for the un-nested recipes, as well as the symlinks.

I've chosen by default to print issues, whereas an auto-fix can be attempted with `--fix`

**Comment by jolheiser** [comment]
This admittedly got a little messier than I would have liked, but it works on my windows machine.

Arguably it would be easier without a non-fix option, but I still think it's nice to default to a non-destructive action,

**Pull request merged**
