### PR TITLE
update go-yaml to 3.0.1

### PR DESCRIPTION
**Pull request by candrewlee14**
Closing #29

### CODE REVIEW

**Comment by jolheiser** [comment]
This didn't actually update the code being used. Need to change anywhere using the old `go-yaml` path in source.

**Comment by candrewlee14** [comment]
Sorry, doesn't upgrading from 3.0.0 to 3.0.1 allow keeping the same paths in files?

**Comment by jolheiser** [comment]
It would, but we weren't using 3.0.0
The current import is `github.com/go-yaml/yaml` which is using a non-module version (I suspect this is actually older than v2, but am not at a computer to check)
The new import is `gopkg.in/yaml.v3`

**Comment by candrewlee14** [comment]
Oh wow, nice catch. Thanks for letting me know, I'll get that fixed.

**Pull request merged**
