### PR TITLE
New latest strategy

### PR DESCRIPTION
**Pull request by enr**
Hi,
i would like to use webman to install non-github/gitea software, eg Maven.
To do this I created a new latest strategy (`fixed`, maybe you can find a better name).
An example of a working recipe definition is in `testcases/pkgs/maven.webman-pkg.yml`.

`go run main.go -l testcases add maven`

Cheers, Enrico

### CODE REVIEW

**Comment by jolheiser** [comment]
Wouldn't an archlinux strategy work?
https://github.com/archlinux/svntogit-community/blob/master/maven/trunk/PKGBUILD

**Comment by enr** [comment]
Hi @jolheiser ,
actually archlinux strategy works :)
At the moment I can't think of a case where it might not be enough, maybe some windows-only software, so feel free to close the PR (or keep it if you think this code can be useful as a starting point for a new strategy).
Thank you, Enrico

**Comment by jolheiser** [comment]
Awesome, glad it works! 🍵

**Comment by enr** [comment]
Just to add that it might be useful for managing private packages (e.g. at some corporate environment)

**Comment by candrewlee14** [comment]
Good point, I'll keep that in mind. For now, I'll leave this unmerged for now until someone wants to install a package from maven with no working alternative.

**Pull request closed without merging**
