### PR TITLE
Move from unpack to archiver

### PR DESCRIPTION
**Pull request by jolheiser**
Leaving as draft, `bintest` fails on Windows, specifically non-windows binaries.

I checked, and this was true prior to archiver, so it's not _specific_ to this PR, but I may as well fix it at the same time if I can.

On WSL, after moving to archiver, `bintest` succeeded with a handful of packages still.

### CODE REVIEW

**Comment by candrewlee14** [comment]
I'm bot sure it cross-platform extraction can be supported on windows because on of non-Go commands required to decompress xz, and bz2 I think. Let me know what you think.

**Comment by candrewlee14** [comment]
Fantastic! Was there a reason you picked to use v3 of archiver rather than v4?

**Comment by jolheiser** [comment]
> Fantastic! Was there a reason you picked to use v3 of archiver rather than v4?

`v4` is currently unfinished and has fewer tests, so I opted for `v3` which has been stable for quite a while.

> I'll accept that package maintenance/dev-specific commands can allow symlinks enabled with admin privileges, but a standard installation shouldn't require it.

Yes, this is only during bintest, because we force Windows to attempt it the "unix way", whereas normally we'd use a batch file instead of a symlink for normal usage.

**Comment by candrewlee14** [comment]
I think the last change I'd request is that if someone tries to run bintest on windows and runs into symlink errors, it should say something suggesting running from Admin on windows.

**Comment by jolheiser** [comment]
Currently the error looks like this 
```
rg@13.0.0: Failed creating links: symlink ~.webman\test\linux\amd64\pkg\rg\rg-13.0.0\rg ~.webman\test\linux\amd64\bin\rg: A required privilege is not held by the client.
```

Do you want me to make it more succinct?

**Comment by jolheiser** [comment]
I've added a message. While it doesn't explicitly check for "symlink errors", I think it's going to be a common hint on Windows.

Thoughts? Do you want me to check for symlink-specific errors?

**Comment by candrewlee14** [comment]
That'll be good for now, I think that message is clear enough.
Great work!

I think the next big piece that brings all the package maintenance validation together is adding an Action that runs bintest on changed packages. That will mean package maintainers see if their package is valid, and I don't have to do a local installation test to validate & merge new packages.

**Comment by jolheiser** [comment]
> That'll be good for now, I think that message is clear enough. Great work!
> 
> I think the next big piece that brings all the package maintenance validation together is adding an Action that runs bintest on changed packages. That will mean package maintainers see if their package is valid, and I don't have to do a local installation test to validate & merge new packages.

Already working on it 😄 
Should have a PR up shortly over in the other repo

**Pull request merged**
